[workspace]
resolver = "2"
members = [
    "app/hello0",
    "app/hello1",
    "app/loop",
    "app/uname",
    "app/window0",
    "app/window1",
    "dbgutil",
    "e2etest",
    "font",
    "noli",
    "os",
]
default-members = [
    "dbgutil",
    "e2etest",
    "font",
    "noli",
]
