[unstable]
# To solve:
# - can't find crate for `core`
# - can't find crate for `compiler_builtins`
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
# See this json for rustflags
target = "x86_64-unknown-elf.json"
# c.f. https://users.rust-lang.org/t/how-to-pass-cargo-linker-args/3163/3
# c.f. https://darkcoding.net/software/a-very-small-rust-binary-indeed/
# c.f. https://doc.rust-lang.org/rustc/codegen-options/index.html

[profile.release]
strip = true
lto = true
opt-level = "z"
panic = "abort"

[lib]
target = "x86_64-unknown-elf.json"
