[package]
name = "dbgutil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
pdb="0.7.0"
rustc-demangle = "0.1"
anyhow = "1.0.68"
argh = "0.1.9"
lazy_static = "1.4.0"
