[unstable]
# To solve:
# - can't find crate for `core`
# - can't find crate for `compiler_builtins`
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler_builtins_mem"]

[build]
target = "x86_64-unknown-elf.json"
