name: Wasabi OS continuous integration
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    container: hikalium/wasabi-builder:latest
    steps:
      - name: Dump metadata
        run: |
          echo "The job was triggered by a ${{ github.event_name }} event"
          echo "This job is running on a ${{ runner.os }} server hosted by GitHub"
          echo "The name of the branch is ${{ github.ref }} and the repository is ${{ github.repository }}"
      - name: Check out the source code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls .
      - name: Dump config
        run: |
          make dump_config
      - name: Build OS
        run: |
          make
      - name: Build apps
        run: |
          make
      - name: Pre-upload Test
        run: |
          make pre_upload_test
      - name: Post-upload Test
        #if: ${{ false }} # still WIP so disable this temporarily
        run: |
          make post_upload_test
      - name: Report
        run: |
          echo "Done. status: ${{ job.status }}"
